service: serverless-examples

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
    myCustomEnvVar: 7

functions:
  aws-based:
    handler: functions/basics/aws-based.handler
    events:
      - http:
          method: get
          path: aws-based
          cors: true
      - http:
          method: get
          path: aws-based/{proxy+}
          cors: true
  express-based:
    handler: functions/basics/express-based.handler
    events:
      - http:
          method: get
          path: express-based
          cors: true
      - http:
          method: get
          path: express-based/{proxy+}
          cors: true

plugins:
  - serverless-offline
