service: serverless-by-example

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
    DB_URL: ${env:DB_URL}

functions:
  basics-aws-based:
    handler: functions/basics/aws-based.handler
    events:
      - http:
          method: get
          path: basics/aws-based

  basics-express-based:
    handler: functions/basics/express-based.handler
    events:
      - http:
          method: get
          path: basics/express-based

  auth-jwt-generate:
    handler: functions/auth/jwt/generate.handler
    events:
      - http:
          method: post
          path: auth/jwt/generate

  auth-jwt-verify:
    handler: functions/auth/jwt/verify.handler
    events:
      - http:
          method: get
          path: auth/jwt/verify

  db-mongo:
    handler: functions/db/mongo.handler
    events:
      - http:
          method: get
          path: db/mongo

plugins:
  - serverless-offline
