service: serverless-examples

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
    JWT_SECRET: ${opt:jwt-secret}

functions:
  aws-based:
    handler: functions/basics/aws-based.handler
    events:
      - http:
          method: get
          path: aws-based
          cors: true
      - http:
          method: get
          path: aws-based/{proxy+}
          cors: true

  express-based:
    handler: functions/basics/express-based.handler
    events:
      - http:
          method: get
          path: express-based
          cors: true
      - http:
          method: get
          path: express-based/{proxy+}
          cors: true

  auth-jwt-generate:
    handler: functions/auth/jwt/generate.handler
    events:
      - http:
          method: post
          path: auth/jwt/generate

  auth-jwt-verify:
    handler: functions/auth/jwt/verify.handler
    events:
      - http:
          method: get
          path: auth/jwt/verify

plugins:
  - serverless-offline
