service: serverless-examples

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  mongo-connect:
    handler: mongo.handler
    events:
      - http:
          method: get
          path: db/mongo

plugins:
  - serverless-offline
