service: serverless-examples

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  aws-based:
    handler: aws-based.handler
    events:
      - http:
          method: get
          path: aws-based
          cors: true

  express-based:
    handler: express-based.handler
    events:
      - http:
          method: get
          path: express-based
          cors: true

plugins:
  - serverless-offline
